### ISSUE TITLE
Custom font not working

### ISSUE THREAD

**Issue by razvanpaul** [luispadron/UICircularProgressRing#16] opened 2017-02-15 22:27 UTC
Hello! Thank you for this amazing library. I have set this in the IB: "Montserrat-Semibold".
The font is surely imported correctly into the app, because IB shows this:

![snip20170216_1](https://cloud.githubusercontent.com/assets/8782666/22998203/6054c2a0-f3de-11e6-91db-5dfbc4681313.png)

But, it breaks when the table view cell displays it. I get this:
![snip20170216_2](https://cloud.githubusercontent.com/assets/8782666/22998239/876895d8-f3de-11e6-9ce4-bcd081a335f3.png)

I don't modify the cell at all, nor I don't change anything except the progress by calling `setProgress`.

Any ideas why it break? I also tried to set it programatically, exactly same result.

**Comment by luispadron** [comment] 2017-02-15 22:40
That's odd, I just tested (not using a cell just a subview of a view controller) and it's working fine.
Using custom Menlo font, as you can see after animating the font stays the same.

<img width="364" alt="screen shot 2017-02-15 at 5 37 45 pm" src="https://cloud.githubusercontent.com/assets/13840545/22998658/b9e12e14-f3a5-11e6-8ee0-565cbd037e43.png">


Could you send me an example of your project or the project? Post it here or email me at [luis@luispadron.com](mailto:luis@luispadron.com) if you want to keep it private.

**Comment by razvanpaul** [comment] 2017-02-16 06:25
I have already tried to set it programatically, I got the same result.

**Comment by luispadron** [comment] 2017-02-16 08:40
In order to help further I'm going to need an example project or at least some code to see what may be the cause. 

Either link to an example of what you are doing or email me if you prefer to keep your code private.

**Comment by luispadron** [comment] 2017-02-16 18:27
So you sent me the project, regrettably, I am unable to test it due to the requirements of the app. 
However, I went ahead and created a project using a table view controller and table view cells as I thought this may be the cause for why this issue was happening but I am still unable to reproduce.

Here is a screenshot and as you can see the custom font is set correctly, even after animating.

![simulator screen shot feb 16 2017 1 27 01 pm](https://cloud.githubusercontent.com/assets/13840545/23034963/9b341de0-f44b-11e6-8b68-5d83e74b0879.png)

Not sure where to go from here, just try and verify that there isn't any weird stuff going on behind the scenes in your application. Also, make sure the font is correctly imported.

**Comment by luispadron** [comment] 2017-03-01 17:54
Closing this because I cannot replicate the issue and doesn't seem to be happening on any of my projects, please update if you figure anything else out.

**Closed by luispadron** 2017-03-01 17:54 UTC

**Comment by luispadron** [comment] 2017-03-16 18:15
Update on this issue, I have updated the project to include new font system.
Read the release notes in [1.4.0](https://github.com/luispadron/UICircularProgressRing/releases/tag/v1.4.0). This may fix the issue you were previously having
