### ISSUE TITLE
Having this issue in XCode

### ISSUE THREAD

**Issue by h36ahmed** [luispadron/UICircularProgressRing#84] opened 2018-04-09 03:53 UTC
![image](https://user-images.githubusercontent.com/13081913/38478529-4573b256-3b87-11e8-94df-8d835da5416b.png)

I isolated the problem to this pod. It keeps failing, everytime I add UICircleProgressRing to the Storyboard. It may be due IBDesignable or a bug in XCode.

XCode 9.3
Swift 4.1
iOS 11.3

**Comment by shubham14896** [comment] 2018-04-09 07:14
Facing the same problem

**Comment by luispadron** [comment] 2018-04-09 16:12
Are you both using CocoaPods, just tested on a brand new project and I'm experiencing the same thing. I'm looking into the issue now.

**Comment by h36ahmed** [comment] 2018-04-10 02:52
Yes I am using CocoaPods.

**Comment by luispadron** [comment] 2018-04-10 02:59
I tried looking into this today but couldn’t figure out what the issue is. Seems to be a code signing issue but this doesn’t make much sense since it’s a framework and doesn’t need to be signed. Still looking into this

**Comment by shubham14896** [comment] 2018-04-10 04:26
So for of now , implemented via code instead of storyboard , Looking for storyboard fix.

**Comment by lucJW** [comment] 2018-04-10 08:05
I'm also getting the same error, tried with
XCode 9.2 + CocoaPods 1.5.0 and Xcode 9.3 + CocoaPods 1.5.0

**Comment by lucJW** [comment] 2018-04-10 14:32
Yes - with CocoaPods 1.4.0 it works again.
Looks like CocoaPods 1.5.0 removes the "Copy Pods Resources" section from the project files where a shell script is getting executed.

**Comment by luispadron** [comment] 2018-04-12 16:32
It does look like we’re gonna have to wait for a fix from the CocoaPods team for this, or use 1.4.0 in the meantime. I’m going to close this for now since it’s not an issue with this project. 

Feel free to reopen if anything new comes up.

**Closed by luispadron** 2018-04-12 16:32 UTC

**Comment by kiokumicu** [comment] 2018-05-10 09:05
I'm using Carthage, and don't get error on rendering, but render also absent (
Try use last and 1.4.0 version.
Xcode 9.3

**Comment by luispadron** [comment] 2018-05-12 10:49
The Carthage issue is unlike the cocoa pods issue. Carthage has no support for IBDesignable
