### ISSUE TITLE
Failed to render and update auto layout status error

### ISSUE THREAD

**Issue by mohammedtabish** [luispadron/UICircularProgressRing#99] opened 2018-06-02 22:27 UTC
#### Version

Latest

#### Overview of what you tried to do

making view a subclass of UIProgressringView

#### What is the expected outcome?

Progress circle
#### What is the actual outcome?

Failed to render and update auto layout status

#### Post sample code or example here

```swift
ANSWER HERE
```

**Comment by luispadron** [comment] 2018-06-03 22:06
I can't really do much with what you've provided, either provide an example which replicates this issue or give me more information

**Comment by mohammedtabish** [comment] 2018-06-03 22:35
See these pics here 
In this pic [here](http://tinypic.com/r/2is8sg1/9) circular view is not showings on screen but when i build this and run on simulator/device it does shows up
Here [link](http://tinypic.com/r/2u8z912/9) is the error i got when i link the view to the Circular Progress Ring Class FIle

Ps: - I have already tried reinstalling my xcode and did pod updated the cocoa pods , still the same error

**Comment by luispadron** [comment] 2018-06-03 22:37
This is a duplicate of #84, and not something I can fix.

**Closed by luispadron** 2018-06-03 22:37 UTC
Labels: duplicate
