### ISSUE TITLE
How can i Pause this animation for some time can you explain me

### ISSUE THREAD

**Issue by maulik6994** [luispadron/UICircularProgressRing#37] opened 2017-04-28 13:30 UTC
READ BEFORE POSTING AN ISSUE

_Not following these guidelines may result in me ignoring or closing your issue, please carefully read and submit an appropriate issue as it helps with time and fixes._

#### Please provide the current version of the library you are using

- Version = 

#### Have you read the documentation?

- [x] Yes 
- [ ] No
 
	If no, read the docs [here](http://htmlpreview.github.io/?https://github.com/luispadron/UICircularProgressRing/blob/master/docs/index.html) before posting an issue

#### Is it a bug? Provide the following
- Detailed overview of what you are trying to accomplish
- What is the expected outcome?
- What is the actualy outcome?
- Either post sample code, or example project where isssue can be recreated

#### Is it a question? Provide the following

- Has it be answered [here](https://github.com/luispadron/UICircularProgressRing/issues?utf8=✓&q=) before?
- Be detailed and describe the question in detail
- If it's a question about something that is happening within your code base, either post a small amount of code, [email me](mailto:luis@luispadron.com) project if you want to keep it private, or post an example project where I can try to assist
- Please do your own research before posting any questions which may have been asked on StackOverFlow before. 
- Make sure to communicate back and keep issue updated or it will be closed

#### Is it a feature request? Provide the following

- Does it make sense to put this in the project? Why
- Is it something that can be done in a reasonable amount of time?
- Will it effect anyone currently using the lib?
- Have you tried to implement this and submit a pull request, if no, why not?

_If you have read all of this please follow the template and post the issue. Thanks for using UICiruclarProgressRing._

**Comment by luispadron** [comment] 2017-04-28 13:42
Duplicate of #36

**Closed by luispadron** 2017-04-28 13:42 UTC
